### ISSUE TITLE
Issue during import using webpack+babel

### ISSUE THREAD

**Issue by ByJC** [Wildhoney/Legofy#12]
Hi @Wildhoney, 

I encounter an issue using your legofy.

I tried to import legofy using 

``` js
import {transform} from 'legofy'
```

into my project which currently use Webpack and babel and I get this error : 

```
ERROR in ./~/legofy/src/core.js
Module parse failed: /Users/byjc/Workspace/test/angular-es6-webpack-boilerplate/node_modules/legofy/src/core.js Line 17: Unexpected token
You may need an appropriate loader to handle this file type.
|  * @type {Object}
|  */
| export const DEFAULTS = {
|     FACTOR: 0.05,
|     BLEND_MODE: 'overlay'
 @ ./lib/components/legofy/legofy.controller.js 7:14-31
```

I used Babel : 

``` js
    "babel-core": "~6.5.1",
    "babel-loader": "~6.2.2",
    "babel-preset-es2015": "~6.5.0",
```

and this is my conf webpack : 

``` js
var path = require('path'),
    webpack = require("webpack"),
    libPath = path.join(__dirname, 'lib'),
    wwwPath = path.join(__dirname, 'www'),
    pkg = require('./package.json'),
    HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: path.join(libPath, 'index.js'),
    output: {
        path: path.join(wwwPath),
        filename: 'bundle-[hash:6].js'
    },
    babel: {
        presets: ['es2015']
    },
    module: {
        loaders: [{
            test: /\.html$/,
            loader: 'file?name=templates/[name]-[hash:6].html'
        }, {
            test: /\.(png|jpg)$/,
            loader: 'file?name=img/[name].[ext]' // inline base64 URLs for <=10kb images, direct URLs for the rest
        }, {
            test: /\.css$/,
            loader: "style!css"
        }, {
            test: /\.scss$/,
            loader: "style!css!autoprefixer!sass"
        }, {
            test: /\.js$/,
            exclude: /(node_modules)/,
            loader: "ng-annotate?add=true!babel"
        }, {
            test: [/fontawesome-webfont\.svg/, /fontawesome-webfont\.eot/, /fontawesome-webfont\.ttf/, /fontawesome-webfont\.woff/, /fontawesome-webfont\.woff2/],
            loader: 'file?name=fonts/[name].[ext]'
        }]
    },
    plugins: [
        new HtmlWebpackPlugin({
            filename: 'index.html',
            pkg: pkg,
            template: path.join(libPath, 'index.html')
        }),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
    ]
};
```

I'm aware this is not directly about your component but I can't find a way to load it properly and don't know what kind of loader i should use for the core.js

Thanks,

**Comment by Wildhoney** [comment]
By default Webpack will exclude the `node_modules` directory: `exclude: /(node_modules)/`.

If you remove that it will compile, but really Legofy should have a compiled file in its repository, which I'll do now :+1: Thanks.

**Comment by ByJC** [comment]
Thanks for the explanation and the modification !

**Comment by Wildhoney** [comment]
No problem... Please let me know if you have any further issues with Legofy @ByJC

**Comment by ByJC** [comment]
Hi @Wildhoney !
I just tested the modification you made yesterday and if you change in the package.json the attributes main without generate the core.js into /dist, it causes the following error : 

```
Error: Cannot resolve module 'legofy' in [...]
```

As long as the compiled file is not generated maybe it's a good thing not to change the package.json ?

**Comment by Wildhoney** [comment]
@ByJC Sorry &ndash; my fault! Please try now.

**Comment by Wildhoney** [comment]
Also moved to Webpck for the compilation.

**Comment by ByJC** [comment]
Last question : 
When i Legofy my images, they change to one single size : 
![Image](http://s27.postimg.org/dz06vhog3/Screen_Shot_2016_02_12_at_4_07_26_PM.png)

I just made a transform and nothing else, no styles or anything.
is there a property to force the legofy image to be the same size as before ?

**Comment by Wildhoney** [comment]
@ByJC Legofy wasn't setting the `svg` element's `height` and `width` if they weren't supplied to the `img` node &mdash; you could have fixed it by supplying the height and width explicitly.

I think I've fixed this in [`v0.1.11`](https://github.com/Wildhoney/Legofy/blob/master/src/core.js#L111) though &mdash; please see if it resolves it.

**Comment by ByJC** [comment]
@Wildhoney it's working perfectly !
thanks for your reactivity :)

**Comment by Wildhoney** [comment]
:+1: Happy Legofying!

**Comment by ByJC** [comment]
Your work inspired me, so here an angular's directive to legofy images : https://github.com/ByJC/angular-legofy

Hope you like it

**Comment by Wildhoney** [comment]
@ByJC awesome! I've [added it](https://github.com/Wildhoney/Legofy#legofy) to the README :beers:
